name: Feature request
description: Suggest an idea for Curio Dashboard
labels: ["enhancement"]
body:
  - type: textarea
    id: request
    attributes:
      label: What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the motivation or the problem is.
      placeholder: Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Add any other context, design docs or screenshots about the feature request here.
    validations:
      required: false
